version: '3.8'

services:
  database:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=contact-list-app
    volumes:
      - pgdata:/data/postgres
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname==node3

  cache:
    image: redis:alpine
    restart: always
    ports: 
      - 6379:6379
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname==node4

  app:
    image: gagigante/tpe-app:latest
    restart: always
    ports: 
      - 3333:3333
    environment:
      - DATABASE_USER=user
      - DATABASE_PASS=pass
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=contact-list-app
      - REDIS_HOST=cache
    volumes: 
      - .:/usr/app  
    depends_on:
      - database
      - cache
    deploy:
      mode: replicated
      replicas: 5

volumes:
  pgdata:
    driver: local
